tracksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.dynamoDbTable}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: title
        AttributeType: S
      - AttributeName: artist
        AttributeType: S
    GlobalSecondaryIndexes:
      - IndexName: GSI
        KeySchema:
          - AttributeName: title
            KeyType: HASH
          - AttributeName: artist
            KeyType: RANGE
        Projection:
          ProjectionType: KEYS_ONLY
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
    KeySchema:
      - AttributeName: id
        KeyType: HASH
